replicaCount: 1

image:
  repository: 875306317082.dkr.ecr.us-east-2.amazonaws.com/agora-server
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  protocol: TCP
  name: agora-server

ingress:
  enabled: true  # Set this to true to enable Ingress
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx  # Use your Ingress controller's class if different
  hosts:
    - host: api.agorasquare.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: agorasquare-tls-secret  # Use your TLS secret name
      hosts:
        - api.agorasquare.io

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

initialDelaySeconds: 60
